#Create a file name as credetials and paste the following with working keys
# [default]
# aws_access_key_id=AKIA2QEFLENWN2DW5O6K
# aws_secret_access_key=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
# docker secret create aws_creds credentials
# Use the above created secret mounted to /home/root/.aws/credentials as shown below.
#--------------------------------------------------------------------------------------
version: '3.3'
services:
  db:
    image: sreeharshav/utils
    secrets:
      - source: aws_creds
        target: /root/.aws/credentials
        uid: '1000'
        gid: '1000'
        mode: 0700
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      resources:
        reservations:
          memory: 128M
        limits:
         memory: 512M
    environment:
      AWS_DEFAULT_REGION: us-east-1
    networks:
      - appnet
secrets:
  aws_creds:
    external: true
networks:
  appnet:

